export const USER_ON_LOGIN_REQUESTED = 'USER_ON_LOGIN_REQUESTED';
export const USER_ON_LOGIN_SUCCEEDED = 'USER_ON_LOGIN_SUCCEEDED';
export const USER_ON_LOGIN_FAILED = 'USER_ON_LOGIN_FAILED';

export const USER_ON_SIGN_UP_REQUESTED = 'USER_ON_SIGN_UP_REQUESTED';
export const USER_ON_SIGN_UP_SUCCEEDED = 'USER_ON_SIGN_UP_SUCCEEDED';
export const USER_ON_SIGN_UP_FAILED = 'USER_ON_SIGN_UP_FAILED';
